// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwtsqe7z1MVvqdg5pYJ4lw7cca2gWVZcQ',
    appId: '1:896146979100:web:99c830393b6b19fd0f22d9',
    messagingSenderId: '896146979100',
    projectId: 'jarnama-app-8a54d',
    authDomain: 'jarnama-app-8a54d.firebaseapp.com',
    storageBucket: 'jarnama-app-8a54d.appspot.com',
    measurementId: 'G-H2ZKCZRJCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO48uvRQvNTyXBiANw1sIH-8T8HQTUhFo',
    appId: '1:896146979100:android:19e0c12906d23ae40f22d9',
    messagingSenderId: '896146979100',
    projectId: 'jarnama-app-8a54d',
    storageBucket: 'jarnama-app-8a54d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOx0m2NhERscFw7m7ekKPUHhEi-PDOCa8',
    appId: '1:896146979100:ios:15da2fcbed7371230f22d9',
    messagingSenderId: '896146979100',
    projectId: 'jarnama-app-8a54d',
    storageBucket: 'jarnama-app-8a54d.appspot.com',
    iosClientId: '896146979100-t8olspkr6v7erm4jkvpb144kpik1n3a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOx0m2NhERscFw7m7ekKPUHhEi-PDOCa8',
    appId: '1:896146979100:ios:15da2fcbed7371230f22d9',
    messagingSenderId: '896146979100',
    projectId: 'jarnama-app-8a54d',
    storageBucket: 'jarnama-app-8a54d.appspot.com',
    iosClientId: '896146979100-t8olspkr6v7erm4jkvpb144kpik1n3a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
